//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioSwitcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioSwitcher.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Automatically switch to plugged in device.
        /// </summary>
        internal static string AutomaticallySwitchToPluggedInDevice {
            get {
                return ResourceManager.GetString("AutomaticallySwitchToPluggedInDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultCommunicationsDevice {
            get {
                object obj = ResourceManager.GetObject("DefaultCommunicationsDevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultMultimediaDevice {
            get {
                object obj = ResourceManager.GetObject("DefaultMultimediaDevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string DeviceState_Active {
            get {
                return ResourceManager.GetString("DeviceState_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default communications device.
        /// </summary>
        internal static string DeviceState_DefaultCommunicationsDevice {
            get {
                return ResourceManager.GetString("DeviceState_DefaultCommunicationsDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default device.
        /// </summary>
        internal static string DeviceState_DefaultDevice {
            get {
                return ResourceManager.GetString("DeviceState_DefaultDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default multimedia device.
        /// </summary>
        internal static string DeviceState_DefaultMultimediaDevice {
            get {
                return ResourceManager.GetString("DeviceState_DefaultMultimediaDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string DeviceState_Disabled {
            get {
                return ResourceManager.GetString("DeviceState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not present.
        /// </summary>
        internal static string DeviceState_NotPresent {
            get {
                return ResourceManager.GetString("DeviceState_NotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not plugged in.
        /// </summary>
        internal static string DeviceState_Unplugged {
            get {
                return ResourceManager.GetString("DeviceState_Unplugged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Disabled {
            get {
                object obj = ResourceManager.GetObject("Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices selected.
        /// </summary>
        internal static string NoDevices {
            get {
                return ResourceManager.GetString("NoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playback devices.
        /// </summary>
        internal static string NoPlaybackDevices {
            get {
                return ResourceManager.GetString("NoPlaybackDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recording devices.
        /// </summary>
        internal static string NoRecordingDevices {
            get {
                return ResourceManager.GetString("NoRecordingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NotificationArea {
            get {
                object obj = ResourceManager.GetObject("NotificationArea", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotPresent {
            get {
                object obj = ResourceManager.GetObject("NotPresent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlaybackDevice {
            get {
                object obj = ResourceManager.GetObject("PlaybackDevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RecordingDevice {
            get {
                object obj = ResourceManager.GetObject("RecordingDevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Run at Windows startup.
        /// </summary>
        internal static string RunAtStartup {
            get {
                return ResourceManager.GetString("RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default &amp;communication device.
        /// </summary>
        internal static string SetAsDefaultComunicationDevice {
            get {
                return ResourceManager.GetString("SetAsDefaultComunicationDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default &amp;multimedia device.
        /// </summary>
        internal static string SetAsDefaultMultimediaDevice {
            get {
                return ResourceManager.GetString("SetAsDefaultMultimediaDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Disabled devices.
        /// </summary>
        internal static string ShowDisabledDevices {
            get {
                return ResourceManager.GetString("ShowDisabledDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Not present devices.
        /// </summary>
        internal static string ShowNotPresentDevices {
            get {
                return ResourceManager.GetString("ShowNotPresentDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Playback devices.
        /// </summary>
        internal static string ShowPlaybackDevices {
            get {
                return ResourceManager.GetString("ShowPlaybackDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Recording devices.
        /// </summary>
        internal static string ShowRecordingDevices {
            get {
                return ResourceManager.GetString("ShowRecordingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unplugged devices.
        /// </summary>
        internal static string ShowUnpluggedDevices {
            get {
                return ResourceManager.GetString("ShowUnpluggedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Switcher.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unplugged {
            get {
                object obj = ResourceManager.GetObject("Unplugged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
