name: Build Audio Switcher
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
     
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
          versionSpec: '5.2.x'
    
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.2
      
    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@09ef42ede5677d811d1eca1c6810ec057bd38aa3
      with:
        version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
        assemblyVersion: ${{ steps.gitversion.outputs.assemblySemVer }}
        fileVersion: ${{ steps.gitversion.outputs.majorMinorPatch }}
        informationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}  
    
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore src\AudioSwitcher.sln
 
    - name: Build and Publish Application
      run: msbuild src\AudioSwitcher.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=src\AudioSwitcher\Properties\PublishProfiles\FolderProfile.pubxml
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AudioSwitcher-${{ steps.gitversion.outputs.nuGetVersionV2 }}
        path: src\AudioSwitcher\bin\Release\net48\win7-x86\
